name: emngly
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - filelock=3.13.1
  - fsspec=2024.6.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - ld_impl_linux-64=2.40
  - libabseil=20240116.2
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libprotobuf=4.25.3
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.3
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=1.1.1w
  - pandas=2.2.3
  - pip=24.2
  - python=3.11.0
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytorch=2.3.1
  - pytz=2024.1
  - readline=8.2
  - scikit-learn=1.5.1
  - scipy=1.14.1
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - sympy=1.13.2
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tqdm=4.66.5
  - typing_extensions=4.11.0
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
